apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: eddcp/gitops-fc
  newTag: 66c4174c44e9643e22df1bb077072c97f7494c6c
